name: CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -C debuginfo=0

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            os: windows-latest
          - name: macOS aarch64
            os: macos-latest
          - name: Linux x64
            os: ubuntu-latest
          - name: Linux aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Build library
        run: cargo build --lib

      - name: Build all examples
        run: cargo build --workspace --bins
